package com.atemtrainer.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006876)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EEFFF)
val onPrimaryContainerLight = Color(0xFF001F24)
val secondaryLight = Color(0xFF4A6267)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7EC)
val onSecondaryContainerLight = Color(0xFF051F23)
val tertiaryLight = Color(0xFF525E7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E2FF)
val onTertiaryContainerLight = Color(0xFF0E1B36)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)

val primaryDark = Color(0xFF53D7F0)
val onPrimaryDark = Color(0xFF00363E)
val primaryContainerDark = Color(0xFF004E59)
val onPrimaryContainerDark = Color(0xFF9EEFFF)
val secondaryDark = Color(0xFFB1CBD0)
val onSecondaryDark = Color(0xFF1B3438)
val secondaryContainerDark = Color(0xFF324A4F)
val onSecondaryContainerDark = Color(0xFFCDE7EC)
val tertiaryDark = Color(0xFFBBC6E8)
val onTertiaryDark = Color(0xFF24304C)
val tertiaryContainerDark = Color(0xFF3A4664)
val onTertiaryContainerDark = Color(0xFFD9E2FF)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE4E5)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDDE4E5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
